executor: CeleryExecutor

fernetKey: "9KJ6htugZBkj1fx0tyC-TihllprmknF32agnpHFt9_o="
webserverSecretKey: "mywebserversecret123"

images:
  airflow:
    repository: srinivasa594/airflow-dbt
    tag: latest
    pullPolicy: Always

apiServer:
  enabled: true

# ✅ FIX: use global env (your chart supports this)
env:
  - name: CELERYD_NODENAME
    value: "worker@%h"

postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow

  primary:
    persistence:
      enabled: false

  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: latest

redis:
  enabled: true

dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: https://github.com/srirama9908-lang/Inpatient_snoeflakedbt.git
    branch: master
    subPath: airflow/dags

logs:
  persistence:
    enabled: false