executor: SequentialExecutor

postgresql:
  enabled: true

redis:
  enabled: false

dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: https://github.com/srirama9908-lang/Inpatient_snoeflakedbt.git
    branch: main
    subPath: dags

logs:
  persistence:
    enabled: false

webserver:
  service:
    type: LoadBalancer

scheduler:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

triggerer:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi